export const theme = {
  colors: {
    bg: '#ffffff',
    surface: '#ffffff',
    surface2: '#fafafa',
    ink: '#0f0f0f',
    ink2: '#404040',
    muted: '#737373',
    faint: '#a3a3a3',
    border: '#e5e5e5',
    borderStrong: '#d4d4d4',
    accent: '#10b981',
    accentInk: '#065f46',
    accentSoft: '#ecfdf5',
    danger: '#dc2626',
    overlay: 'rgba(0,0,0,0.5)',
  },
  radii: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
    '2xl': 20,
    pill: 999,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    '2xl': 24,
    '3xl': 32,
  },
  font: {
    sans: 'Manrope',
    mono: 'JetBrainsMono-Regular',
    monoBold: 'JetBrainsMono-Bold',
    monoExtraBold: 'JetBrainsMono-ExtraBold',
  },
  type: {
    xs: 11,
    sm: 12,
    base: 13,
    md: 14,
    lg: 15,
    xl: 17,
    '2xl': 20,
    '3xl': 24,
    '4xl': 28,
    '5xl': 36,
  },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 24,
      elevation: 12,
    },
  },
};
