export const EMPTY_PROFILE = {
  firstName: '',
  lastName: '',
  name: '',
  email: '',
  phone: '',
  address: '',
  city: '',
  state: '',
  zipCode: '',
  country: '',
  linkedIn: '',
  portfolio: '',
  github: '',
  currentTitle: '',
  currentCompany: '',
  yearsExperience: 0,
  coverLetter: '',
  salary: '',
  startDate: '',
  skills: '',
  experience: [],
  education: [],
};

export const PROFILE_FIELD_LABELS = {
  firstName: 'First Name',
  lastName: 'Last Name',
  name: 'Full Name',
  email: 'Email',
  phone: 'Phone',
  address: 'Address',
  city: 'City',
  state: 'State',
  zipCode: 'Zip Code',
  country: 'Country',
  linkedIn: 'LinkedIn URL',
  portfolio: 'Portfolio URL',
  github: 'GitHub URL',
  currentTitle: 'Current Job Title',
  currentCompany: 'Current Company',
  yearsExperience: 'Years of Experience',
  coverLetter: 'Cover Letter',
  salary: 'Expected Salary',
  startDate: 'Available Start Date',
  skills: 'Skills (comma-separated)',
};
